repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        args: [ --unsafe ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: poetry-check
        name: validate pyproject.toml
        entry: poetry check
        language: system
        pass_filenames: false
        files: ^pyproject\.toml$
      - id: poetry-lock
        name: check poetry.lock
        entry: poetry check --lock
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort app/
        language: system
        types: [ python ]
      - id: black
        name: black
        entry: poetry run black app/
        language: system
        types: [ python ]
      - id: mypy
        name: mypy
        entry: poetry run mypy app/
        language: system
        types: [ python ]
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        types: [ python ]
        pass_filenames: false
